/**
 * Created by Kuba on 06.12.2017.
 */

public with sharing class UtilConstants {
    public static final String emptyInput = 'You have to type text to be solved';
    public static final String emptyInputOrTooShortInput = 'You have to type text to be solved or you didn\'t type required lines of text';
    public static final String ex1 = 'SayingHello';
    public static final String ex2 = 'CountingNumbers';
    public static final String ex3 = 'PrintingQuotes';
    public static final String ex4 = 'MadLib';
    public static final String ex5 = 'SimpleMath';
    public static final String ex6 = 'RetirementCalculator';
}